### ISSUE TITLE
transformer 运行报错

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/benchmark#134]
```bash
[2019-06-21 16:52:25,962 INFO train.py:655] Namespace(batch_size=4096, device='GPU', enable_ce=False, fetch_steps=100, local=True, opts=['learning_rate', '2.0', 'warmup_steps', '8000', 'beta2', '0.997', 'd_model', '1024', 'd_inner_hid', '4096', 'n_head', '16', 'prepostprocess_dropout', '0.3', 'attention_dropout', '0.1', 'relu_dropout', '0.1', 'weight_sharing', 'True', 'pass_num', '100', 'max_length', '256'], pool_size=200000, shuffle=True, shuffle_batch=True, sort_type='pool', special_token=['<s>', '<e>', '<unk>'], src_vocab_fpath='data/vocab.bpe.32000', sync=True, token_delimiter=' ', train_file_pattern='data/train.tok.clean.bpe.32000.en-de', trg_vocab_fpath='data/vocab.bpe.32000', update_method='pserver', use_mem_opt=True, use_py_reader=True, use_token_batch=True, val_file_pattern=None)
[2019-06-21 16:52:26,259 INFO train.py:706] before adam
memory_optimize is deprecated. Use CompiledProgram and Executor
[2019-06-21 16:52:52,269 INFO train.py:724] local start_up:
[2019-06-21 16:52:52,270 INFO train.py:506] init fluid.framework.default_startup_program
W0621 16:52:53.971729  7661 device_context.cc:259] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.0, Runtime API Version: 9.0
W0621 16:52:53.983120  7661 device_context.cc:267] device: 0, cuDNN Version: 7.4.
[2019-06-21 16:52:54,789 INFO train.py:509] begin reader
Traceback (most recent call last):
  File "train.py", line 806, in <module>
    train(args)
  File "train.py", line 726, in train
    token_num, predict, pyreader)
  File "train.py", line 515, in train_loop
    py_reader_provider_wrapper=py_reader_provider_wrapper)
  File "train.py", line 347, in prepare_data_generator
    train_reader = py_reader_provider_wrapper(data_reader, )
TypeError: py_reader_provider_wrapper() takes exactly 2 arguments (1 given)
```

**Comment by chengduoZH** [comment]
已经修复
