### ISSUE TITLE
auto_run_paddle.sh执行的时候，paddingRnn总是会会在large model出现错误

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/benchmark#63]
```bash
2019-05-13 18:45:34,470 - lm - INFO - Running with args : Namespace(batch_size=20, data_path='data/simple-examples/data/', enable_ce=True, inference_only=False, init_params_path=None, log_path=None, max_epoch=5, model_type='large', parallel=True, profile=False, rnn_model='static', save_model_dir=None, use_gpu=True)
2019-05-13 18:45:34,470-INFO: Running with args : Namespace(batch_size=20, data_path='data/simple-examples/data/', enable_ce=True, inference_only=False, init_params_path=None, log_path=None, max_epoch=5, model_type='large', parallel=True, profile=False, rnn_model='static', save_model_dir=None, use_gpu=True)
W0513 18:45:37.997777  8668 device_context.cc:261] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.0, Runtime API Version: 9.0
W0513 18:45:38.010324  8668 device_context.cc:269] device: 0, cuDNN Version: 7.0.
W0513 18:45:38.077817  8668 graph.h:204] WARN: After a series of passes, the current graph can be quite different from OriginProgram. So, please avoid using the `OriginProgram()` method!
2019-05-13 18:45:38,082-WARNING: 
     You can try our memory optimize feature to save your memory usage:
         # create a build_strategy variable to set memory optimize option
         build_strategy = compiler.BuildStrategy()
         build_strategy.enable_inplace = True
         build_strategy.memory_optimize = True
         
         # pass the build_strategy to with_data_parallel API
         compiled_prog = compiler.CompiledProgram(main).with_data_parallel(
             loss_name=loss.name, build_strategy=build_strategy)
      
     !!! Memory optimize is our experimental feature !!!
         some variables may be removed/reused internal to save memory usage, 
         in order to fetch the right value of the fetch_list, please set the 
         persistable property to true for each variable in fetch_list

         # Sample
         conv1 = fluid.layers.conv2d(data, 4, 5, 1, act=None) 
         # if you need to fetch conv1, then:
         conv1.persistable = True

                 
I0513 18:45:39.936303  8668 build_strategy.cc:305] SeqOnlyAllReduceOps:0, num_trainers:1
begin to load data
vocab word num 10000
finished load data
Traceback (most recent call last):
  File "train.py", line 512, in <module>
    main()
  File "train.py", line 506, in main
    train()
  File "train.py", line 421, in train
    train_ppl = train_an_epoch(epoch_id, batch_times)
  File "train.py", line 393, in train_an_epoch
    use_program_cache=True)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 640, in run
    return_numpy=return_numpy)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/executor.py", line 502, in _run_parallel
    exe.run(fetch_var_names, fetch_var_name)
paddle.fluid.core.EnforceNotMet: Invoke operator reshape2 error.
Python Callstacks: 
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 1700, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/layers/nn.py", line 6590, in reshape
    "XShape": x_shape})
  File "/home/crim/benchmark/PaddingRNN/lstm_paddle/lm_model.py", line 250, in lm_model
    init_hidden, shape=[num_layers, -1, hidden_size])
  File "train.py", line 192, in main
    rnn_model=rnn_model)
  File "train.py", line 512, in <module>
    main()
C++ Callstacks: 
holder_ should not be null
Tensor not initialized yet when Tensor::type() is called. at [/paddle/paddle/fluid/framework/tensor.h:146]
PaddlePaddle Call Stacks: 
0       0x7f06f362b468p void paddle::platform::EnforceNotMet::Init<std::string>(std::string, char const*, int) + 360
1       0x7f06f362b7b7p paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int) + 87
2       0x7f06f362c24bp paddle::framework::Tensor::type() const + 107
3       0x7f06f3eb83e8p paddle::operators::ReshapeKernel::operator()(paddle::framework::ExecutionContext const&) const + 312
4       0x7f06f536c6e0p paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, paddle::framework::RuntimeContext*) const + 368
5       0x7f06f536c97ap paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) const + 218
6       0x7f06f536a0fcp paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 332
7       0x7f06f5177ceap paddle::framework::details::ComputationOpHandle::RunImpl() + 250
8       0x7f06f516a3e0p paddle::framework::details::OpHandleBase::Run(bool) + 160
9       0x7f06f50c823dp
10      0x7f06f50c909dp paddle::framework::details::ThreadedSSAGraphExecutor::RunOp(std::shared_ptr<paddle::framework::BlockingQueue<paddle::framework::details::VarHandleBase*> > const&, paddle::framework::details::OpHandleBase*) + 1325
11      0x7f06f50cf3ebp paddle::framework::details::ThreadedSSAGraphExecutor::RunImpl(std::vector<std::string, std::allocator<std::string> > const&) + 1339
12      0x7f06f50ccc32p paddle::framework::details::ThreadedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 482
13      0x7f06f50b8b9ap paddle::framework::details::ScopeBufferedSSAGraphExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&) + 378
14      0x7f06f37e2132p paddle::framework::ParallelExecutor::Run(std::vector<std::string, std::allocator<std::string> > const&, std::string const&) + 562
15      0x7f06f361a60ep
16      0x7f06f36605d6p
17            0x4c5326p PyEval_EvalFrameEx + 37958
18            0x4b9b66p PyEval_EvalCodeEx + 774
19            0x4c1f56p PyEval_EvalFrameEx + 24694
20            0x4b9b66p PyEval_EvalCodeEx + 774
21            0x4c17c6p PyEval_EvalFrameEx + 22758
22            0x4b9b66p PyEval_EvalCodeEx + 774
23            0x4c1f56p PyEval_EvalFrameEx + 24694
24            0x4b9b66p PyEval_EvalCodeEx + 774
25            0x4c1f56p PyEval_EvalFrameEx + 24694
26            0x4b9b66p PyEval_EvalCodeEx + 774
27            0x4c1f56p PyEval_EvalFrameEx + 24694
28            0x4b9b66p PyEval_EvalCodeEx + 774
29            0x4eb69fp
30            0x4e58f2p PyRun_FileExFlags + 130
31            0x4e41a6p PyRun_SimpleFileExFlags + 390
32            0x4938cep Py_Main + 1358
33      0x7f077fb53830p __libc_start_main + 240
34            0x493299p _start + 41
```

**Comment by ccmeteorljh** [comment]
fixed
