### ISSUE TITLE
transformer 多进程单卡下报错

### ISSUE THREAD

**Issue by ccmeteorljh** [PaddlePaddle/benchmark#81]
https://github.com/PaddlePaddle/benchmark/blob/master/NeuralMachineTranslation/Transformer/fluid/train/train.py#L616

```bash
2019-05-21 09:29:28,729-INFO: Namespace(batch_size=4096, device='GPU', enable_ce=True, fetch_steps=100, local=True, opts=['dropout_seed', '10', 'learning_rate', '2.0', 'warmup_steps', '8000', 'beta2', '0.997', 'd_model', '512', 'd_inner_hid', '2048', 'n_head', '8', 'prepostprocess_dropout', '0.1', 'attention_dropout', '0.1', 'relu_dropout', '0.1', 'weight_sharing', 'True', 'pass_num', '1', 'model_dir', 'tmp_models', 'ckpt_dir', 'tmp_ckpts'], pool_size=200000, shuffle=False, shuffle_batch=False, sort_type='pool', special_token=['<s>', '<e>', '<unk>'], src_vocab_fpath='data/vocab.bpe.32000', sync=True, token_delimiter=' ', train_file_pattern='data/train.tok.clean.bpe.32000.en-de', trg_vocab_fpath='data/vocab.bpe.32000', update_method='pserver', use_default_pe=False, use_mem_opt=True, use_py_reader=True, use_token_batch=True, val_file_pattern=None)
Traceback (most recent call last):
  File "train.py", line 784, in <module>
    train(args)
  File "train.py", line 641, in train
    dev_count = get_device_num()
  File "train.py", line 616, in get_device_num
    device_num = subprocess.check_output(['nvidia-smi','-L']).decode().count('\n')
NameError: global name 'subprocess' is not defined
```

**Comment by chengduoZH** [comment]
@ccmeteorljh 为什么是多进程单卡？
没有设置环境变量（CUDA_VISIBLE_DEVICES）？

**Comment by ccmeteorljh** [comment]
> @ccmeteorljh 为什么是多进程单卡？
> 没有设置环境变量（CUDA_VISIBLE_DEVICES）？

设置了，想试试多进程模式下单卡和单进程单卡下的速度对比如何，上面那个问题import一下就可以了，但是运行还是会报错
```bash
2019-05-21 11:29:16,022-INFO: Namespace(batch_size=4096, device='GPU', enable_ce=True, fetch_steps=100, local=True, opts=['dropout_seed', '10', 'learning_rate', '2.0', 'warmup_steps', '8000', 'beta2', '0.997', 'd_model', '512', 'd_inner_hid', '2048', 'n_head', '8', 'prepostprocess_dropout', '0.1', 'attention_dropout', '0.1', 'relu_dropout', '0.1', 'weight_sharing', 'True', 'pass_num', '1', 'model_dir', 'tmp_models', 'ckpt_dir', 'tmp_ckpts'], pool_size=200000, shuffle=False, shuffle_batch=False, sort_type='pool', special_token=['<s>', '<e>', '<unk>'], src_vocab_fpath='data/vocab.bpe.32000', sync=True, token_delimiter=' ', train_file_pattern='data/train.tok.clean.bpe.32000.en-de', trg_vocab_fpath='data/vocab.bpe.32000', update_method='pserver', use_default_pe=False, use_mem_opt=True, use_py_reader=True, use_token_batch=True, val_file_pattern=None)
2019-05-21 11:29:16,534-INFO: before adam
2019-05-21 11:29:17,550-INFO: local start_up:
2019-05-21 11:29:17,550-INFO: init fluid.framework.default_startup_program
Traceback (most recent call last):
  File "train.py", line 785, in <module>
    train(args)
  File "train.py", line 703, in train
    token_num, predict, pyreader)
  File "train.py", line 467, in train_loop
    exe.run(startup_prog)
  File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/executor.py", line 625, in run
    use_program_cache=use_program_cache)
  File "/opt/python/cp27-cp27mu/lib/python2.7/site-packages/paddle/fluid/executor.py", line 702, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core.EnforceNotMet: out of memory at [/paddle/paddle/fluid/platform/device_context.cc:245]
PaddlePaddle Call Stacks: 
0       0x7f0739be0aa0p void paddle::platform::EnforceNotMet::Init<char const*>(char const*, char const*, int) + 352
1       0x7f0739be0e19p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 137
2       0x7f073b9c9dd3p paddle::platform::CUDADeviceContext::CUDADeviceContext(paddle::platform::CUDAPlace) + 3171
3       0x7f073b9ce158p _ZNSt17_Function_handlerIFSt10unique_ptrIN6paddle8platform13DeviceContextESt14default_deleteIS3_EEvESt17reference_wrapperISt12_Bind_simpleIFZNS2_20EmplaceDeviceContextINS2_17CUDADeviceContextENS2_9CUDAPlaceEEEvPSt3mapIN5boost7variantISC_NS2_8CPUPlaceENS2_15CUDAPinnedPlaceENSE_6detail7variant5void_ESK_SK_SK_SK_SK_SK_SK_SK_SK_SK_SK_SK_SK_SK_SK_SK_EESt13shared_futureIS6_ESt4lessISL_ESaISt4pairIKSL_SN_EEESL_EUlvE_vEEEE9_M_invokeERKSt9_Any_data + 104
4       0x7f073b9cc73ap std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()(), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::unique_ptr<paddle::platform::DeviceContext, std::default_delete<paddle::platform::DeviceContext> > > >::_M_invoke(std::_Any_data const&) + 42
5       0x7f0739cb00f7p std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()()>&, bool&) + 39
6       0x7f08100bde03p pthread_once + 83
7       0x7f073b9cfa2cp _ZNSt13__future_base15_Deferred_stateISt12_Bind_simpleIFZN6paddle8platform20EmplaceDeviceContextINS3_17CUDADeviceContextENS3_9CUDAPlaceEEEvPSt3mapIN5boost7variantIS6_NS3_8CPUPlaceENS3_15CUDAPinnedPlaceENS8_6detail7variant5void_ESE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_SE_EESt13shared_futureISt10unique_ptrINS3_13DeviceContextESt14default_deleteISI_EEESt4lessISF_ESaISt4pairIKSF_SM_EEESF_EUlvE_vEESL_E15_M_run_deferredEv + 220
8       0x7f073b9c9f69p paddle::platform::DeviceContextPool::Get(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 137
9       0x7f073b86988dp paddle::framework::GarbageCollector::GarbageCollector(boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, paddle::platform::CUDAPinnedPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&, unsigned long) + 477
10      0x7f073b869b11p paddle::framework::UnsafeFastGPUGarbageCollector::UnsafeFastGPUGarbageCollector(paddle::platform::CUDAPlace const&, unsigned long) + 33
11      0x7f0739d606d0p paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool) + 480
12      0x7f0739d614afp paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool) + 143
13      0x7f0739bd082ep
14      0x7f0739c15f56p
15      0x7f08103d9ce8p PyEval_EvalFrameEx + 28264
16      0x7f08103dc37dp PyEval_EvalCodeEx + 2061
17      0x7f08103d9d70p PyEval_EvalFrameEx + 28400
18      0x7f08103dc37dp PyEval_EvalCodeEx + 2061
19      0x7f08103d9d70p PyEval_EvalFrameEx + 28400
20      0x7f08103dc37dp PyEval_EvalCodeEx + 2061
21      0x7f08103d9d70p PyEval_EvalFrameEx + 28400
22      0x7f08103d9e9ep PyEval_EvalFrameEx + 28702
23      0x7f08103dc37dp PyEval_EvalCodeEx + 2061
24      0x7f08103dc4b2p PyEval_EvalCode + 50
25      0x7f08104061c2p PyRun_FileExFlags + 146
26      0x7f0810407559p PyRun_SimpleFileExFlags + 217
27      0x7f081041d1ddp Py_Main + 3149
28      0x7f080f6b0d20p __libc_start_main + 256
29            0x4006b1p
```

**Comment by QianShengWu** [comment]
> 设置了，想试试多进程模式下单卡和单进程单卡下的速度对比如何，上面那个问题import一下就可以了

老哥，你怎么解决的，求教，我也出现同样的问题

**Comment by chengduoZH** [comment]
@QianShengWu 目前还不支持多进程单卡模式
