### ISSUE TITLE
运行maskrcnn-from-fb有报错

### ISSUE THREAD

**Issue by xiegegege** [PaddlePaddle/benchmark#92]
使用8卡运行maskrcnn-from-fb，在训练结束后的test阶段有如下报错：
`2019-05-23 04:24:31,288 maskrcnn_benchmark.trainer INFO: Total training time: 1 day, 18:53:50.877918 (0.8579 s / it)
Traceback (most recent call last):
  File "./tools/train_net.py", line 174, in <module>
    main()
  File "./tools/train_net.py", line 170, in main
    run_test(cfg, model, args.distributed)
  File "./tools/train_net.py", line 95, in run_test
    data_loaders_val = make_data_loader(cfg, is_train=False, is_distributed=distributed)
  File "/benchmark/benchmark/Mask-RCNN/maskrcnn-from-fb/maskrcnn_benchmark/data/build.py", line 154, in make_data_loader
    datasets = build_dataset(dataset_list, transforms, DatasetCatalog, is_train)
  File "/benchmark/benchmark/Mask-RCNN/maskrcnn-from-fb/maskrcnn_benchmark/data/build.py", line 33, in build_dataset
    data = dataset_catalog.get(dataset_name)
  File "/benchmark/benchmark/Mask-RCNN/maskrcnn-from-fb/maskrcnn_benchmark/config/paths_catalog.py", line 113, in get
    attrs = DatasetCatalog.DATASETS[name]
KeyError: 'coco_2017_minival'`

**Comment by xiegegege** [comment]
需要将配置文件中的coco_2017_minival修改为coco_2017_val
